baseURL = "https://rich.liebling.us"
title = "Rich Liebling"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
footnoteReturnLinkContents="↩"

theme = "engimo"

disqusShortname = ""
googleAnalytics = "UA-131321686-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "On Software, Strategy and Leadership"
title404 = "Nothing's here!"

[params.assets]

favicon = "/images/favicon.ico"
customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
customJS = []
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "rliebling"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = false
accentColor = "#44ccff"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
#sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
sidebar = ["about","sidebar_menu","taxonomy_cloud","social_menu"]
footer = []

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "blog@liebling.us"
github = "rliebling"
linkedin = "richliebling"

[params.comments]
enable = true

[params.comments.staticman]
enable = true
apiEndpoint = "https://dev.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "rliebling"
repository = "my_blog"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "rliebling"
repository = "engimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Github"
weight = -110  # used to sort the menu
identifier = "github"
url = "https://github.com/rliebling"

[[menu.main]]
name = "Linked In"
weight = -10
identifier = "linkedin"
url = "https://www.linkedin.com/in/richliebling/"

[[menu.main]]
name = "About"
weight = 10
identifier = "about"
url = "/about"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
